### PR TITLE
Add any unused url_kwargs from formatting the template as parameters

### PR DESCRIPTION
**Pull request by davehunt**
This feature allows for more dynamic URLs. Any `url_kwargs` that do not appear in the `URL_TEMPLATE` as placeholders will be added to the query string parameters for the URL.

@davidemoro I'm not aware of many people using PyPOM, but if you still are, perhaps you could review on this enhancement? Thanks in advance!

### CODE REVIEW

**Comment by davidemoro** [comment]
Sure!
See you tomorrow.

Thanks,

davide

**Comment by davidemoro** [comment]
Hi @davehunt (cc @diannelli @soulrebel),

all looks fine and this PR should not raise any issue in our code base. Thanks!

I've included some additional test scenarios here, some of them failing, trying to make url parametrization as consistent as possible in special cases taking inspiration from the python requests library because it implements a similar feature using params:
* https://github.com/davehunt/PyPOM/pull/1

Could you review my test cases please? :)

**Comment by davehunt** [comment]
Thanks @davidemoro your tests look great! Do we need to also cover when a collection is passed that matches a template placeholder? I've invited you to collaborate on my fork, so you should be able to push your changes to my branch. Are you interested also in helping to get those tests passing? If not, I'll try to get to them soon.

**Comment by davidemoro** [comment]
Hi @davehunt, sure!

Unfortunately I don't have enough spare time but my colleague @diannelli will be very happy in helping you making those tests passing.

**Comment by davehunt** [comment]
I've added your tests @davidemoro and they're now passing for me locally. Would you mind reviewing my changes? Maybe we could get a v2.0 out soon?

**Pull request merged**
