### PR TITLE
[WIP] remove phantomjs in splinter_driver

### PR DESCRIPTION
**Pull request by davidemoro**
splinter 0.9.0 drops phantomjs support

Notes:
* I have some problems launching tests locally against the original mozilla/PyPOM so I am not able to verify locally if all tests are fine because of this error https://pastebin.com/SrnbWKi8. I am going to verify if the travis build goes fine
* I didn't updated the news.rst

### CODE REVIEW

**Comment by davidemoro** [comment]
Same problem on travis, I am going to investigate in the next days.

See:

* https://github.com/pypa/pipenv/issues/2924

**Comment by davehunt** [comment]
Thanks @davidemoro are you okay for this to wait until the pipenv/pip issues are resolved? Is the issue that Travis CI is installing the latest version of pip, which is incompatible with pipenv? We're already pinning pipenv, and I wouldn't expect the version of pip in Travis CI to change.

**Comment by davidemoro** [comment]
Hi @davehunt, it worked fine upgrading the pipenv version. There is still a problem with flake8 due to a pipenv lock hashes. What do you suggest to do?

**Comment by davehunt** [comment]
I've just updated the dependencies locally, which should fix the missing hashes. I opened a pull request but something odd has happened and GitHub is not showing the pull request, but won't let me open it again. Feel free to run `pipenv update` locally to update the Pipfile. If this passes then we can merge. I'm also attempting to set up Dependabot to keep better track of our depenendencies.

**Comment by davehunt** [comment]
I cherry-picked and merged this in #94 thank you! Do you need a new release?

**Comment by davidemoro** [comment]
Thanks @davehunt!
A new release would be very welcome because people using pypom in
conjunction with splinter won't be able to upgrade the splinter version
until this fix will be fixed.

Il mar 23 ott 2018 18:23 Dave Hunt <notifications@github.com> ha scritto:

**Comment by davehunt** [comment]
I've released PyPOM 2.2.0: https://pypi.org/project/PyPOM/2.2.0/

**Comment by davidemoro** [comment]
Thanks!

**Pull request closed without merging**
